#!/bin/bash

# 🚨 CLOUDFLARE DOMAIN COLLISION FIX SCRIPT
# This script provides the complete steps to fix the domain collision issue

echo "🚨 CLOUDFLARE DOMAIN COLLISION FIX - COMPLETE WORKFLOW"
echo "======================================================"
echo ""
echo "PROBLEM IDENTIFIED:"
echo "- rinawarp-stripe-worker has rinawarptech.com attached (WRONG)"
echo "- rinawarptech project has NO domain attached (CORRECT PROJECT)"
echo ""
echo "🎯 SOLUTION: Move domain from Stripe Worker to Website Project"
echo ""
echo "COMPLETE STEPS TO FOLLOW:"
echo ""
echo "1️⃣  REMOVE DOMAIN FROM STRIPE WORKER (CRITICAL - DO THIS FIRST):"
echo "   • Go to: https://dash.cloudflare.com/pages"
echo "   • Click: 'rinawarp-stripe-worker' project"
echo "   • Go to: 'Custom domains' tab"
echo "   • Click: 'rinawarptech.com'"
echo "   • Click: 'Remove domain'"
echo "   • Confirm removal"
echo ""
echo "2️⃣  ATTACH DOMAIN TO WEBSITE PROJECT:"
echo "   • Click: 'rinawarptech' project (the website)"
echo "   • Go to: 'Custom domains' tab"
echo "   • Click: 'Set up a custom domain'"
echo "   • Enter: 'rinawarptech.com'"
echo "   • Click: 'Continue'"
echo ""
echo "3️⃣  DNS SETUP (What you're seeing now):"
echo "   • Cloudflare will show CNAME setup screen"
echo "   • Log into your DNS provider (where you bought rinawarptech.com)"
echo "   • Add CNAME record:"
echo "     Name: rinawarptech.com (or @)"
echo "     Target: rinawarptech.pages.dev"
echo "   • Save changes"
echo "   • Return to Cloudflare and click 'Check DNS records'"
echo ""
echo "4️⃣  CLEAR CACHES:"
echo "   • Go to: https://dash.cloudflare.com/caching"
echo "   • Click: 'Configuration' tab"
echo "   • Click: 'Purge Everything'"
echo "   • Confirm purge"
echo ""
echo "5️⃣  WAIT FOR DNS PROPAGATION:"
echo "   • DNS changes take 5 minutes to 24 hours globally"
echo "   • Test with: nslookup rinawarptech.com"
echo "   • Visit: https://rinawarptech.com"
echo ""
echo "✅ VERIFICATION (after DNS propagation):"
echo "   • Website shows your actual content (not Stripe Worker code)"
echo "   • New deployments appear immediately"
echo "   • _headers file is served correctly"
echo "   • Stripe Worker still works on /api/* routes"
echo ""
echo "🔧 THIS FIXES:"
echo "   • Changes not appearing"
echo "   • Cache headers not updating"
echo "   • Old designs reappearing"
echo "   • _headers file not being served"
echo "   • Deployment caching issues"
echo ""
echo "⚠️  CRITICAL NOTES:"
echo "   • Step 1 MUST be completed before Step 2"
echo "   • Don't delete rinawarp-stripe-worker, just remove main domain"
echo "   • DNS propagation time varies by provider"
echo "   • Keep Stripe Worker for API routes only"