#!/bin/bash

# RinaWarp Terminal Pro - Complete Production Deployment Script
echo "🚀 RinaWarp Terminal Pro - Complete Production Deployment"
echo "=========================================================="

# Check if running as root (required for system changes)
if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run as root: sudo $0"
  exit 1
fi

# Configuration variables
DOMAIN="rinawarptech.com"
BACKEND_PORT="3001"
NGINX_CONFIG="/etc/nginx/sites-available/rinawarptech"

echo "📋 Configuration:"
echo "   Domain: $DOMAIN"
echo "   Backend Port: $BACKEND_PORT"
echo "   Nginx Config: $NGINX_CONFIG"
echo ""

# Step 1: Install required packages
echo "📦 Step 1: Installing required packages..."
apt update
apt install -y nginx certbot python3-certbot-nginx nodejs npm pm2

echo "✅ Packages installed"

# Step 2: Setup backend server
echo "🔧 Step 2: Setting up backend server..."
cd /home/karina/Documents/Rinawarp-Platforms/src/domain/terminal

# Check if .env exists
if [ ! -f ".env" ]; then
    echo "❌ .env file not found!"
    echo "📝 Please create .env file with your API keys first"
    exit 1
fi

# Install dependencies
npm install

# Stop any existing processes
pm2 stop rinawarp-backend-server 2>/dev/null || true
pm2 delete rinawarp-backend-server 2>/dev/null || true

# Start with PM2
pm2 start ecosystem.config.cjs --only rinawarp-backend-server
pm2 save
pm2 startup

echo "✅ Backend server deployed"

# Step 3: Configure Nginx
echo "🌐 Step 3: Configuring Nginx..."

# Create Nginx configuration
cat > $NGINX_CONFIG << EOF
# RinaWarp Terminal Pro - Nginx Configuration for $DOMAIN
# Redirect all HTTP traffic to HTTPS
server {
    listen 80;
    server_name $DOMAIN www.$DOMAIN;
    return 301 https://\$host\$request_uri;
}

# Secure HTTPS server
server {
    listen 443 ssl http2;
    server_name $DOMAIN www.$DOMAIN;

    # SSL certificates (these will be auto-generated by Certbot)
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.cloudflareinsights.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; default-src 'self' http: https: data: blob:;" always;

    # Proxy settings for backend API
    location /api/ {
        proxy_pass http://localhost:$BACKEND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;

        # CORS headers for API
        add_header Access-Control-Allow-Origin https://$DOMAIN always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization" always;

        # Handle preflight requests
        if (\$request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin https://$DOMAIN;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
            add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization";
            add_header Access-Control-Max-Age 1728000;
            add_header Content-Type 'text/plain charset=UTF-8';
            add_header Content-Length 0;
            return 204;
        }
    }

    # WebSocket endpoint for real-time features
    location /stream {
        proxy_pass http://localhost:$BACKEND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }

    # Health check endpoint
    location /health {
        proxy_pass http://localhost:$BACKEND_PORT;
        proxy_connect_timeout 5s;
        proxy_send_timeout 5s;
        proxy_read_timeout 5s;
    }

    # Static file serving for frontend
    location / {
        proxy_pass http://localhost:$BACKEND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;

        # Cache static assets
        location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff2|ttf|svg|webp)$ {
            expires 30d;
            access_log off;
            add_header Cache-Control "public, immutable";
        }
    }

    # Rate limiting for API endpoints
    location /api/ {
        limit_req_zone \$binary_remote_addr zone=api:10m rate=10r/s;
        limit_req zone=api burst=20 nodelay;
    }

    # Logs
    access_log /var/log/nginx/rinawarptech.access.log;
    error_log /var/log/nginx/rinawarptech.error.log warn;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private must-revalidate auth;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json;
}
EOF

# Enable the site
ln -s $NGINX_CONFIG /etc/nginx/sites-enabled/

# Test and restart Nginx
nginx -t
systemctl restart nginx

echo "✅ Nginx configured"

# Step 4: Setup SSL with Certbot
echo "🔐 Step 4: Setting up SSL certificates..."
certbot --nginx -d $DOMAIN -d www.$DOMAIN --non-interactive --agree-tos --email admin@$DOMAIN

# Enable auto-renewal
systemctl enable certbot.timer
systemctl start certbot.timer

echo "✅ SSL certificates installed"

# Step 5: Final configuration
echo "⚙️ Step 5: Final configuration..."

# Update frontend API URL
sed -i "s|window.__API_URL__ = '/api/create-checkout-session'|window.__API_URL__ = 'https://$DOMAIN/api/create-checkout-session'|g" /home/karina/Documents/Rinawarp-Platforms/public/music-video/index.html

# Update domain in .env
sed -i "s/DOMAIN=.*/DOMAIN=$DOMAIN/g" /home/karina/Documents/Rinawarp-Platforms/src/domain/terminal/.env

echo "✅ Configuration updated"

# Step 6: Restart services
echo "🔄 Step 6: Restarting services..."
pm2 restart rinawarp-backend-server
systemctl restart nginx

echo "✅ Services restarted"

# Step 7: Test deployment
echo "🧪 Step 7: Testing deployment..."
sleep 5

echo ""
echo "📊 Testing endpoints:"
echo "   Health check: curl -s https://$DOMAIN/health"
echo "   API test: curl -s -X POST https://$DOMAIN/api/create-checkout-session -H 'Content-Type: application/json' -d '{\"plan\": \"music_creator_monthly\", \"email\": \"test@example.com\"}'"

# Test health endpoint
if curl -s https://$DOMAIN/health | grep -q "ok"; then
    echo "✅ Health check passed"
else
    echo "⚠️ Health check failed - check server logs"
fi

echo ""
echo "🎉 Deployment Complete!"
echo "=========================="
echo "🌐 Frontend: https://$DOMAIN"
echo "🔗 API: https://$DOMAIN/api/create-checkout-session"
echo "💊 Health: https://$DOMAIN/health"
echo "📊 PM2 Status: pm2 status"
echo "🌐 Nginx Status: systemctl status nginx"
echo ""
echo "📋 Management Commands:"
echo "   View logs: pm2 logs rinawarp-backend-server"
echo "   Restart backend: pm2 restart rinawarp-backend-server"
echo "   Restart nginx: systemctl restart nginx"
echo "   Check SSL: certbot certificates"
echo ""
echo "⚠️ Next Steps:"
echo "   1. Update Stripe webhook URL to: https://$DOMAIN/api/webhook"
echo "   2. Test subscription flow at: https://$DOMAIN/music-video"
echo "   3. Monitor logs: pm2 logs rinawarp-backend-server --lines 50"