#!/bin/bash

# Stripe Compliance URLs Generator
# Generates the exact URLs needed for Stripe Dashboard compliance

# Configuration
BASE_URL="https://rinawarptech.com"
LEGAL_HUB_PATH="/legal"

# Generate Stripe-compliant URLs
STRIPE_TOS_URL="$BASE_URL$LEGAL_HUB_PATH/terms-of-service.html"
STRIPE_PRIVACY_URL="$BASE_URL$LEGAL_HUB_PATH/privacy-policy.html"

# Output the URLs in a format ready for Stripe Dashboard
echo "📋 RinaWarp Technologies LLC - Stripe Compliance URLs"
echo "================================================="
echo ""
echo "Generated on: $(date)"
echo "Base URL: $BASE_URL"
echo ""
echo "🔹 STRIPE DASHBOARD SETTINGS"
echo "================================================="
echo ""
echo "1. Billing Settings → Customer Portal"
echo "   Terms of Service URL:"
echo "   $STRIPE_TOS_URL"
echo ""
echo "   Privacy Policy URL:"
echo "   $STRIPE_PRIVACY_URL"
echo ""
echo "2. Products → Product Metadata (for each product)"
echo "   Add custom metadata fields:"
echo "   - terms_of_service_url: $STRIPE_TOS_URL"
echo "   - privacy_policy_url: $STRIPE_PRIVACY_URL"
echo ""
echo "3. Terminal Pro License System"
echo "   Update license server configuration:"
echo "   - TOS_URL: $STRIPE_TOS_URL"
echo "   - PRIVACY_URL: $STRIPE_PRIVACY_URL"
echo ""
echo "4. AI-MVC Credit System"
echo "   Update credit purchase flow:"
echo "   - termsUrl: $STRIPE_TOS_URL"
echo "   - privacyUrl: $STRIPE_PRIVACY_URL"
echo ""
echo "5. Checkout Function Metadata"
echo "   Ensure all checkout sessions include:"
echo "   - terms_of_service: $STRIPE_TOS_URL"
echo "   - privacy_policy: $STRIPE_PRIVACY_URL"
echo ""
echo "🔹 VALIDATION CHECKLIST"
echo "================================================="
echo "✓ URLs use HTTPS (secure)"
echo "✓ URLs are absolute (full path)"
echo "✓ URLs resolve to live documents"
echo "✓ Documents are mobile-responsive"
echo "✓ Documents include proper branding"
echo "✓ Documents have effective dates"
echo ""
echo "🔹 STRIPE DASHBOARD LOCATIONS"
echo "================================================="
echo "1. Settings → Business Settings → Customer Portal"
echo "2. Products → [Each Product] → Metadata"
echo "3. Billing → Subscriptions → Customer Portal"
echo "4. Developers → API Keys → Webhook Settings"
echo ""
echo "📎 COPY-PASTE READY VALUES"
echo "================================================="
echo "Terms of Service URL:"
echo "$STRIPE_TOS_URL"
echo ""
echo "Privacy Policy URL:"
echo "$STRIPE_PRIVACY_URL"
echo ""
echo "✅ URLs generated successfully!"
echo "After deploying the Legal Hub, verify these URLs are accessible"
echo "before updating Stripe Dashboard settings."