#!/bin/bash

# 🌐 CLOUDFLARE DNS UPDATE COMMANDS
# Run these in Cloudflare DNS after adding domain to Netlify

echo "🌐 CLOUDFLARE DNS CONFIGURATION"
echo "==============================="
echo ""
echo "📋 DNS Records to configure in Cloudflare:"
echo "1. Remove these old A records (if they exist):"
echo "   ❌ A rinawarptech.com → [VM IP ADDRESS]"
echo "   ❌ A www → [VM IP ADDRESS]"
echo ""
echo "2. Add these CNAME records:"
echo "   ✅ CNAME rinawarptech.com → rinawarptech-website.netlify.app"
echo "   ✅ CNAME www → rinawarptech-website.netlify.app"
echo ""
echo "⚠️  IMPORTANT: Set Proxy status to 'DNS only' (Gray Cloud)"
echo "   This is required for Netlify SSL to work properly"
echo ""
echo "🔄 After making DNS changes:"
echo "   - Wait 1-3 minutes for propagation"
echo "   - Test: https://rinawarptech.com"
echo "   - Verify SSL certificate is active"
echo ""
echo "📞 If DNS doesn't propagate quickly:"
echo "   - Clear browser cache"
echo "   - Try incognito/private browsing"
echo "   - Wait up to 24 hours for full propagation"
echo ""
echo "✅ SUCCESS INDICATORS:"
echo "   - Site loads from Netlify (not VM)"
echo "   - Green lock icon (SSL active)"
echo "   - Fast loading times"
echo "   - No 404 /qzje/ errors"