#!/bin/bash

echo "🔧 ORACLE CLOUD NETWORKING MANUAL FIX GUIDE"
echo "============================================"
echo ""
echo "Since CLI has permission issues, here are your options:"
echo ""
echo "📋 OPTION 1: Web Console (Recommended)"
echo "----------------------------------------"
echo "1. Go to https://cloud.oracle.com"
echo "2. Sign in to your Oracle Cloud account"
echo "3. Navigate to: Compute → Instances"
echo "4. Find and click on: Rinawarp-Api"
echo "5. Click on 'Networking' tab"
echo "6. Click on the subnet name/link"
echo "7. Click on 'Security Lists'"
echo "8. Click on the security list name"
echo "9. Click 'Add Ingress Rules'"
echo "10. Add these rules:"
echo ""
echo "   Rule 1 - SSH:"
echo "   - Source Type: CIDR"
echo "   - Source: 0.0.0.0/0"
echo "   - Destination Type: PORT_RANGE"
echo "   - Destination Port Range: 22"
echo "   - Protocol: TCP"
echo ""
echo "   Rule 2 - HTTP:"
echo "   - Source Type: CIDR"
echo "   - Source: 0.0.0.0/0"
echo "   - Destination Type: PORT_RANGE"
echo "   - Destination Port Range: 80"
echo "   - Protocol: TCP"
echo ""
echo "   Rule 3 - HTTPS:"
echo "   - Source Type: CIDR"
echo "   - Source: 0.0.0.0/0"
echo "   - Destination Type: PORT_RANGE"
echo "   - Destination Port Range: 443"
echo "   - Protocol: TCP"
echo ""
echo "   Rule 4 - API:"
echo "   - Source Type: CIDR"
echo "   - Source: 0.0.0.0/0"
echo "   - Destination Type: PORT_RANGE"
echo "   - Destination Port Range: 3001"
echo "   - Protocol: TCP"
echo ""
echo "11. Click 'Add Ingress Rule'"
echo "12. Wait 3-5 minutes for changes to propagate"
echo ""
echo "📋 OPTION 2: Fix OCI CLI Configuration"
echo "---------------------------------------"
echo "If you want to use CLI, try:"
echo ""
echo "1. Check current configuration:"
echo "   cat ~/.oci/config"
echo ""
echo "2. Re-setup OCI CLI:"
echo "   oci setup config"
echo ""
echo "3. Test with a simpler command:"
echo "   oci compute instance list --compartment-id YOUR_COMPARTMENT_ID"
echo ""
echo "4. If still failing, you may need:"
echo "   - API key with different permissions"
echo "   - Different user/tenancy access"
echo "   - Group policy updates"
echo ""
echo "📋 OPTION 3: Quick CLI Fix (If permissions work)"
echo "-------------------------------------------------"
echo "Run these commands once CLI is working:"
echo ""
echo "# Get security list ID"
echo 'SUBNET_ID=$(oci compute instance list --compartment-id COMPARTMENT_ID --display-name "Rinawarp-Api" --output table | grep -E "subnet|ocid1.subnet" | head -1 | awk "{print \$NF}")'
echo ""
echo "# Add security rules"
echo 'oci network security-list ingress-security-rule add --security-list-id $SECURITY_LIST_ID --protocol "6" --source-type "CIDR" --source "0.0.0.0/0" --destination-type "PORT_RANGE" --destination-port-range-min 22 --destination-port-range-max 22'
echo 'oci network security-list ingress-security-rule add --security-list-id $SECURITY_LIST_ID --protocol "6" --source-type "CIDR" --source "0.0.0.0/0" --destination-type "PORT_RANGE" --destination-port-range-min 80 --destination-port-range-max 80'
echo 'oci network security-list ingress-security-rule add --security-list-id $SECURITY_LIST_ID --protocol "6" --source-type "CIDR" --source "0.0.0.0/0" --destination-type "PORT_RANGE" --destination-port-range-min 443 --destination-port-range-max 443'
echo 'oci network security-list ingress-security-rule add --security-list-id $SECURITY_LIST_ID --protocol "6" --source-type "CIDR" --source "0.0.0.0/0" --destination-type "PORT_RANGE" --destination-port-range-min 3001 --destination-port-range-max 3001'
echo ""
echo "🎯 After ANY option, verify with:"
echo "bash test-networking-connectivity.sh"
echo ""
echo "✅ The web console method (Option 1) is most reliable!"