#!/bin/bash
set -euo pipefail

echo "====================================================="
echo "        🔒 RINAWARP CERTIFICATE HEALING TOOL"
echo "====================================================="
echo "Production Setup: rinawarptech.com"
echo "Port 3001: API Service Only"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# =====================================================
# STEP 1: DIAGNOSE CURRENT CERTIFICATE STATUS
# =====================================================
diagnose_certificates() {
    log_info "🔍 Step 1: Diagnosing current certificate status..."
    
    echo ""
    echo "--- Certificate Files ---"
    if [ -d "/etc/letsencrypt/live" ]; then
        ls -la /etc/letsencrypt/live/
    else
        log_error "No Let's Encrypt certificates found!"
        return 1
    fi
    
    echo ""
    echo "--- Renewal Configuration ---"
    if [ -d "/etc/letsencrypt/renewal" ]; then
        ls -la /etc/letsencrypt/renewal/
    fi
    
    echo ""
    echo "--- NGINX Configuration ---"
    sudo nginx -t 2>/dev/null || log_warn "NGINX configuration has issues"
    
    echo ""
    echo "--- Active Certificates ---"
    sudo certbot certificates 2>/dev/null || log_warn "No active certificates found"
    
    echo ""
    log_info "Diagnosis complete"
}

# =====================================================
# STEP 2: BACKUP EXISTING CONFIGURATION
# =====================================================
backup_configuration() {
    log_info "💾 Step 2: Backing up existing configuration..."
    
    BACKUP_DIR="/root/rinawarp-cert-backup-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$BACKUP_DIR"
    
    # Backup Let's Encrypt directory
    if [ -d "/etc/letsencrypt" ]; then
        log_info "Backing up /etc/letsencrypt to $BACKUP_DIR"
        sudo cp -r /etc/letsencrypt "$BACKUP_DIR/"
    fi
    
    # Backup NGINX configuration
    if [ -f "/etc/nginx/sites-available/rinawarp" ]; then
        log_info "Backing up NGINX configuration to $BACKUP_DIR"
        sudo cp /etc/nginx/sites-available/rinawarp "$BACKUP_DIR/"
    fi
    
    # Backup NGINX sites-enabled
    if [ -f "/etc/nginx/sites-enabled/rinawarp" ]; then
        log_info "Backing up NGINX sites-enabled to $BACKUP_DIR"
        sudo cp /etc/nginx/sites-enabled/rinawarp "$BACKUP_DIR/"
    fi
    
    echo "$BACKUP_DIR" > /tmp/rinawarp_cert_backup_path
    log_info "Backup completed: $BACKUP_DIR"
}

# =====================================================
# STEP 3: REMOVE INCORRECT CERTIFICATES
# =====================================================
remove_incorrect_certs() {
    log_info "🗑️ Step 3: Removing incorrect certificates..."
    
    # Remove any existing certificates for the domain
    log_info "Removing existing certificates for rinawarptech.com"
    sudo certbot delete --cert-name rinawarptech.com 2>/dev/null || true
    sudo certbot delete --cert-name www.rinawarptech.com 2>/dev/null || true
    
    # Clean up renewal configuration
    if [ -f "/etc/letsencrypt/renewal/rinawarptech.com.conf" ]; then
        log_info "Removing old renewal configuration"
        sudo rm -f /etc/letsencrypt/renewal/rinawarptech.com.conf
    fi
    
    log_info "Incorrect certificates removed"
}

# =====================================================
# STEP 4: GENERATE NEW CERTIFICATES
# =====================================================
generate_new_certificates() {
    log_info "🔐 Step 4: Generating new certificates..."
    
    # Stop NGINX to free port 80
    log_info "Stopping NGINX to free port 80"
    sudo systemctl stop nginx
    
    sleep 2
    
    # Generate new certificate
    log_info "Requesting new Let's Encrypt certificate"
    sudo certbot certonly \
        --standalone \
        --preferred-challenges http \
        --email admin@rinawarptech.com \
        --agree-tos \
        --no-eff-email \
        --domains rinawarptech.com,www.rinawarptech.com
    
    # Restart NGINX
    log_info "Restarting NGINX"
    sudo systemctl start nginx
    
    log_info "New certificates generated successfully"
}

# =====================================================
# STEP 5: UPDATE RENEWAL CONFIGURATION
# =====================================================
update_renewal_config() {
    log_info "⚙️ Step 5: Updating renewal configuration..."
    
    RENEWAL_CONF="/etc/letsencrypt/renewal/rinawarptech.com.conf"
    
    if [ -f "$RENEWAL_CONF" ]; then
        sudo tee "$RENEWAL_CONF" > /dev/null <<EOF
# Renewal configuration for RinaWarp Production
# Automatically generated by rina-cert-heal.sh

renew_before_expiry = 30 days
cert = /etc/letsencrypt/live/rinawarptech.com/fullchain.pem
key = /etc/letsencrypt/live/rinawarptech.com/privkey.pem
chain = /etc/letsencrypt/live/rinawarptech.com/chain.pem
fullchain = /etc/letsencrypt/live/rinawarptech.com/fullchain.pem

# Server settings
server = acme-v02.api.letsencrypt.org/directory

# Account
account = /etc/letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory

# Email notifications
email = admin@rinawarptech.com
agree_tos = True
no-eff-email = True

# Authenticator settings
authenticator = standalone
preferred_challenges = http
EOF
        log_info "Renewal configuration updated"
    else
        log_error "Renewal configuration file not found!"
        return 1
    fi
}

# =====================================================
# STEP 6: UPDATE NGINX CONFIGURATION
# =====================================================
update_nginx_config() {
    log_info "🌐 Step 6: Updating NGINX configuration..."
    
    # Create/update NGINX configuration for production
    sudo tee /etc/nginx/sites-available/rinawarp > /dev/null <<'EOF'
# RinaWarp Production NGINX Configuration
# Generated by rina-cert-heal.sh

server {
    listen 80;
    server_name rinawarptech.com www.rinawarptech.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name rinawarptech.com www.rinawarptech.com;

    # SSL Certificates
    ssl_certificate /etc/letsencrypt/live/rinawarptech.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rinawarptech.com/privkey.pem;

    # SSL Configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Security Headers
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    # API Proxy (Port 3001 - API Service Only)
    location /api/ {
        proxy_pass http://localhost:3001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # CORS Headers
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range";
        
        if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
            add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range";
            add_header Access-Control-Max-Age 1728000;
            add_header Content-Type 'text/plain; charset=utf-8';
            add_header Content-Length 0;
            return 204;
        }
    }

    # Health Check Endpoint
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    # Default location
    location / {
        return 200 "RinaWarp API Server - Production Environment";
        add_header Content-Type text/plain;
    }
}
EOF

    # Enable the site
    sudo ln -sf /etc/nginx/sites-available/rinawarp /etc/nginx/sites-enabled/rinawarp
    
    # Remove default site if it exists
    sudo rm -f /etc/nginx/sites-enabled/default
    
    log_info "NGINX configuration updated"
}

# =====================================================
# STEP 7: VALIDATE CONFIGURATION
# =====================================================
validate_configuration() {
    log_info "✅ Step 7: Validating configuration..."
    
    # Test NGINX configuration
    log_info "Testing NGINX configuration..."
    if sudo nginx -t; then
        log_info "NGINX configuration is valid"
    else
        log_error "NGINX configuration has errors!"
        return 1
    fi
    
    # Check certificate files
    log_info "Checking certificate files..."
    if [ -f "/etc/letsencrypt/live/rinawarptech.com/fullchain.pem" ]; then
        log_info "Full chain certificate exists"
    else
        log_error "Full chain certificate missing!"
        return 1
    fi
    
    if [ -f "/etc/letsencrypt/live/rinawarptech.com/privkey.pem" ]; then
        log_info "Private key exists"
    else
        log_error "Private key missing!"
        return 1
    fi
    
    # Check file permissions
    log_info "Checking certificate permissions..."
    if [ "$(sudo stat -c %a /etc/letsencrypt/live/rinawarptech.com/privkey.pem)" = "600" ]; then
        log_info "Private key permissions are correct (600)"
    else
        log_warn "Fixing private key permissions..."
        sudo chmod 600 /etc/letsencrypt/live/rinawarptech.com/privkey.pem
    fi
    
    log_info "Configuration validation complete"
}

# =====================================================
# STEP 8: RESTART SERVICES
# =====================================================
restart_services() {
    log_info "🔄 Step 8: Restarting services..."
    
    # Restart NGINX
    log_info "Restarting NGINX..."
    sudo systemctl restart nginx
    
    if sudo systemctl is-active --quiet nginx; then
        log_info "NGINX restarted successfully"
    else
        log_error "NGINX failed to start!"
        return 1
    fi
    
    # Restart API service if it exists
    if sudo systemctl is-active --quiet rinawarp-api; then
        log_info "Restarting RinaWarp API service..."
        sudo systemctl restart rinawarp-api
    fi
    
    # Start PM2 processes if they exist
    if command -v pm2 >/dev/null 2>&1; then
        log_info "Restarting PM2 processes..."
        pm2 restart all 2>/dev/null || true
    fi
    
    log_info "Services restarted successfully"
}

# =====================================================
# STEP 9: RUN RENEWAL DRY-RUN
# =====================================================
renewal_dry_run() {
    log_info "🔄 Step 9: Running certificate renewal dry-run..."
    
    # Test renewal process
    if sudo certbot renew --dry-run; then
        log_info "Certificate renewal dry-run successful"
    else
        log_warn "Certificate renewal dry-run had warnings (this may be normal)"
    fi
}

# =====================================================
# STEP 10: FINAL VERIFICATION
# =====================================================
final_verification() {
    log_info "🎉 Step 10: Final verification..."
    
    echo ""
    echo "--- Certificate Status ---"
    sudo certbot certificates 2>/dev/null || log_warn "Could not retrieve certificate status"
    
    echo ""
    echo "--- Service Status ---"
    if sudo systemctl is-active --quiet nginx; then
        log_info "NGINX: Running"
    else
        log_error "NGINX: Not running"
    fi
    
    if sudo systemctl is-active --quiet rinawarp-api; then
        log_info "RinaWarp API: Running"
    else
        log_warn "RinaWarp API: Not running"
    fi
    
    echo ""
    echo "--- Connectivity Test ---"
    
    # Test HTTP to HTTPS redirect
    HTTP_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://rinawarptech.com/health || echo "000")
    if [ "$HTTP_RESPONSE" = "301" ] || [ "$HTTP_RESPONSE" = "302" ]; then
        log_info "HTTP to HTTPS redirect: Working"
    else
        log_warn "HTTP to HTTPS redirect: Issue detected"
    fi
    
    # Test HTTPS connection
    HTTPS_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://rinawarptech.com/health || echo "000")
    if [ "$HTTPS_RESPONSE" = "200" ]; then
        log_info "HTTPS connection: Working"
    else
        log_warn "HTTPS connection: Issue detected (Response: $HTTPS_RESPONSE)"
    fi
    
    echo ""
    echo "====================================================="
    echo "       🎊 CERTIFICATE HEALING COMPLETED!"
    echo "====================================================="
    
    BACKUP_PATH=$(cat /tmp/rinawarp_cert_backup_path 2>/dev/null || echo "Unknown")
    echo "📁 Backup location: $BACKUP_PATH"
    echo "🔒 Certificate: /etc/letsencrypt/live/rinawarptech.com/"
    echo "⚙️ NGINX Config: /etc/nginx/sites-available/rinawarp"
    echo "✅ Status: SSL certificates are now properly configured"
    echo ""
    echo "👉 Next steps:"
    echo "   - Visit https://rinawarptech.com to verify"
    echo "   - Check API endpoints: https://rinawarptech.com/api/"
    echo "   - Monitor renewal: sudo certbot certificates"
    echo "====================================================="
}

# =====================================================
# MAIN EXECUTION
# =====================================================

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

# Trap errors
set -e
trap 'log_error "Script failed at line $LINENO"' ERR

# Main execution
diagnose_certificates
backup_configuration
remove_incorrect_certs
generate_new_certificates
update_renewal_config
update_nginx_config
validate_configuration
restart_services
renewal_dry_run
final_verification

log_info "Certificate healing process completed successfully!"